version: '3'
tasks:
  build:
    desc: 'Builds the application'
    cmds:
      - task: build-css
      - task: build-views
      - task: organize
  build-css:
    desc: 'Builds CSS with tailwind'
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./static/output.css --minify
  build-views:
    desc: 'Builds application views'
    cmds:
      - go tool templ generate
      - go run ./cmd/static-generator/main.go
  organize:
    desc: 'Organize built files into dist/'
    cmds:
      - rm -rf dist/
      - mkdir dist/
      - cp -r static dist
      - mv index.html dist
  # Development Tools
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --cmd="go run ./cmd/server/main.go" --proxy="http://localhost:9000" --open-browser=false
  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./static/output.css --clean
  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./static/output.css --watch
  # Start development server
  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-clean
    cmds:
      - echo "Starting app..."
      - task --parallel tailwind-watch templ
  clean:
    desc: 'Clean up built files'
    cmds:
      - rm -rf dist/
