name: Run Migrations

on:
  push:
    branches:
      - 'main'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run migrations
        run: migrate -database "$DB_URL" -path ./migrations up
        env:
          DB_URL: ${{ secrets.DB_URL }}
